#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d  6 7 8 9 10

bspc config border_width        1 
bspc config window_gap          4
bspc config normal_border_color "#32344a"
bspc config focused_border_color "787c99"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Mouse Cursor
xsetroot -cursor_name left_ptr

# Start Polybar
$HOME/.config/polybar/launch.sh
