#! /bin/sh

# Keybindings
pgrep -x sxhkd > /dev/null || sxhkd &

# Monitors
bspc monitor DP-0 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d  6 7 8 9 10

# Config
bspc config border_radius	8
bspc config border_width        2
bspc config window_gap          10
bspc config top_padding		35
bspc config bottom_padding	0
bspc config left_padding	0
bspc config right_padding	0
bspc config single_monocle	false
bspc config click_to_focus	false
bspc config split_ratio		0.50
bspc config borderless_monocle	true
bspc config gapless_monocle	true

# Coloring
bspc config normal_border_color "#e5e9f0"
bspc config active_border_color "#e5e9f0"
bspc config focused_border_color "#2492e0"

# Mouse Cursor
xsetroot -cursor_name left_ptr

# Start Polybar
$HOME/.config/polybar/launch.sh
